name: staging

on:
  push:
    branches: [ "main"]
  pull_request:
    branches: [ "main"]

job:

  build:

    run-on: ubuntu-latest

    steps:
    - name: Checkout SCM
      uses: actions/checkout@v4

    - name: Build Docker Image
      run: docker build -t literatur-fe:latest

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: $({ secrets.DOCKER_USERNAME })
        password: $({ secrets.DOCKER_TOKEN })

    - name: Push Images
      run: docker push literatur-fe:latest
